<?php

return [
    'default' => [
        'background' => '#FDFDFF',
        'stroke' => '#E4E2E2',
        'title' => '#121212',
        'description' => '#555555',
        'tagBackground' => '#F2F0EF',
        'tagTitle' => '#333333',
    ],
    'light-gray' => [
        'background' => '#F6F8FA',
        'stroke' => '#D0D7DE',
        'title' => '#1F2328',
        'description' => '#4B5563',
        'tagBackground' => '#E4E7EB',
        'tagTitle' => '#374151',
    ],
    'pastel' => [
        'background' => '#FFFBF7',
        'stroke' => '#FAD4C0',
        'title' => '#333333',
        'description' => '#5E5E5E',
        'tagBackground' => '#FFE6D9',
        'tagTitle' => '#993333',
    ],
    'sunny' => [
        'background' => '#FFFBEA',
        'stroke' => '#FCD34D',
        'title' => '#1E293B',
        'description' => '#525252',
        'tagBackground' => '#FEF3C7',
        'tagTitle' => '#78350F',
    ],
    'mint' => [
        'background' => '#E6FFFA',
        'stroke' => '#B2F5EA',
        'title' => '#234E52',
        'description' => '#2C7A7B',
        'tagBackground' => '#CFFAFE',
        'tagTitle' => '#285E61',
    ],
    'dark' => [
        'background' => '#0D1117',
        'stroke' => '#30363D',
        'title' => '#F0F6FC',
        'description' => '#8B949E',
        'tagBackground' => '#21262D',
        'tagTitle' => '#C9D1D9',
    ],
    'carbon' => [
        'background' => '#1C1C1C',
        'stroke' => '#2E2E2E',
        'title' => '#FFFFFF',
        'description' => '#CCCCCC',
        'tagBackground' => '#2A2A2A',
        'tagTitle' => '#B0B0B0',
    ],
    'dracula' => [
        'background' => '#282A36',
        'stroke' => '#44475A',
        'title' => '#F8F8F2',
        'description' => '#BD93F9',
        'tagBackground' => '#44475A',
        'tagTitle' => '#FF79C6',
    ],
    'copper' => [
        'background' => '#F8F1EC',
        'stroke' => '#B87333',
        'title' => '#5C4033',
        'description' => '#7C4A2D',
        'tagBackground' => '#EAD2B7',
        'tagTitle' => '#5C4033',
    ],
    'linux-user' => [
        'background' => '#3b3b72',
        'stroke' => '#ecb1b1',
        'title' => '#8c8c9e',
        'description' => '#9b78e6',
        'tagBackground' => '#828f61',
        'tagTitle' => '#2c2c54',
    ],
];
