#!/bin/sh

cd "$(git rev-parse --show-toplevel)"

# Run PHP syntax check
composer php-lint || exit 1

# Run Prettier formatting check
if ! composer format-check; then
  echo "Prettier check failed! Run 'composer format' to fix formatting."
  exit 1
fi